import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import { NavBar, Header } from '@/layouts'

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Innovathon',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <NavBar/>
        <Header/>
        {children}
      </body>
    </html>
  )
}
