import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { NavBar } from '@/layouts'
/* The code is defining a React component called `RootLayout` that serves as the layout for the
application. It takes in a `children` prop, which represents the content that will be rendered
within the layout. */

const inter = Inter({ subsets: ['latin'] })
/* The code is defining a constant variable `metadata` of type `Metadata`. `Metadata` is likely a
custom type or interface that defines the structure of metadata for the application. In this case,
the `metadata` object has two properties: `title` and `description`. The `title` property is set to
the string 'Innovathon', and the `description` property is set to the string 'Generated by create
next app'. This metadata can be used for various purposes, such as setting the title and description
of the page in the HTML head section. */

export const metadata: Metadata = {
  title: 'Innovathon',
  description: 'Generated by create next app'
}
/**
 * The RootLayout function is a TypeScript React component that renders a basic HTML structure with a
 * NavBar component and the children components.
 * @param  - The `RootLayout` function is a React component that takes in a single parameter called
 * `props`. The `props` object has a property called `children`, which is of type `React.ReactNode`.
 * The `children` prop is used to render the content that is passed into the `RootLayout`
 * @returns The `RootLayout` component is returning an HTML document with a `<body>` element containing
 * a `<NavBar>` component and the `children` prop.
 */

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
